language: node_js
node_js:
- v4
- v5
- v6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
- npm test -- -i --coverage
env:
  global:
  - CXX=g++-4.8
  - MASTER_KEY=t3udI6F9uEc5bHDPQOjokzn9fgfA4wDq
  - JWT_SECRET=WoIR8NWUNPqgvrmcZCR3lRRRwwCKtXt5
deploy:
  provider: heroku
  app: statushub-dev
  api_key:
    secure: tLmUQNWFXgrxOzHX/GsOZT+FZxLPo2NXYwqefsJoZ+yWpsorA8vUO1NnjJt2696V8przcLH2AugcmRBppLdAfYYB2/Dz96kQE0fY6Yx+meKYdLCYlsxd1dvucDDzKxPacS5Pczc8hWPcCIn7ORypVXba32ftQ/ZxDZmdWvDZg+MmCKiNxfO6RAGbRIyyAzyYP025YHZxAbX+2sGRVxtyoLUAg+iuO40zuID8nwm2Mp1SILYpM0rI2zG6up0pjpFqEJuzQzaI0MJzdnUGrEmb2gn6TUxbTtwCfQ+iuH5qajVAI7SrmBnbI6LAIxOU4lb/uyvIbqqwhBYMfIH9KsSXTFRaKLyOej94Q8SoJz6gEdOxnlR2sk2M2b5yn+xqzkwaWWbPUb0aF3tqJ2fuBVPY3hqVEYbzPVZPJFkKQm1TbnAIWtkCmmOb70KSCXIgPmoxCvZAeMHCUCfWoTrEpsnU7xT1wToxaSqyOCQMC4ZP8bYcBAf9IOdqa+EL8yUnIFdZqNH+ErzJv9oix0H1MgL2td2htOD9XLENTdgkNVA7wEGoLr69I9fDCReBA+tXC/9gsvwGABP6jOyzxibujYB3UAL3YGhZToLom/7dnuvnK5AcM11g/YeNZ19I3BKQFQzvoj91LUa2jCYgWMvPPs4+k3pVFeawrC9yBrge03dnIfc=
